name: config tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  smoke:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Enable corepack to fix https://github.com/actions/setup-node/pull/901
        run: corepack enable pnpm

      - name: Use Node.js LTS (22.x)
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install project dependencies
        run: corepack pnpm install --frozen-lockfile

      - name: Run tests
        run: corepack pnpm test
